# Site settings
title: Góc Anh.Nguyen
email: nvtanh.ptit@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Tôi là Nguyễn Văn Trần Anh !..
  Và đây là nơi tôi chia sẻ, viết ra những thứ mình học dc, cảm thấy thú vị và vào những lúc tâm trạng viết lách lên ngôi :v ;))
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: nvtanh
github_username:  nvtanh

# Build settings
markdown: kramdown